{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":288041957,"authorName":"iwaneicher","from":"&quot;iwaneicher&quot; &lt;reicher@...&gt;","profile":"iwaneicher","replyTo":"LIST","senderId":"5PNqkLGqcRp2KinwJKBp6bBjIj1fd7PaeaYYPr4wJhDTGXuI6mS38y_vMTvSgVC7BgT18qp0fYp42VCOoX3bciihybwPTQ","spamInfo":{"isSpam":false,"reason":"0"},"subject":"Re: Null Pointer Exception within Class NEATSpecieManager.java","postDate":"1163150726","msgId":2810,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PGVqMWdpNit0cTcyQGVHcm91cHMuY29tPg==","inReplyToHeader":"PGVqMWU4MSs3MHVwQGVHcm91cHMuY29tPg=="},"prevInTopic":2809,"nextInTopic":2812,"prevInTime":2809,"nextInTime":2811,"topicId":2809,"numMessagesInTopic":3,"msgSnippet":"Hi again, We just looked through the relevant code and most probably found a bug within the class InnovationDatabase.java. Here the code from line 90 to 116 ","rawEmail":"Return-Path: &lt;reicher@...&gt;\r\nX-Sender: reicher@...\r\nX-Apparently-To: neat@yahoogroups.com\r\nReceived: (qmail 84950 invoked from network); 10 Nov 2006 09:26:45 -0000\r\nReceived: from unknown (66.218.66.217)\n  by m36.grp.scd.yahoo.com with QMQP; 10 Nov 2006 09:26:45 -0000\r\nReceived: from unknown (HELO n23.bullet.scd.yahoo.com) (66.94.237.52)\n  by mta2.grp.scd.yahoo.com with SMTP; 10 Nov 2006 09:26:45 -0000\r\nReceived: from [66.218.69.4] by n23.bullet.scd.yahoo.com with NNFMP; 10 Nov 2006 09:25:27 -0000\r\nReceived: from [66.218.66.90] by t4.bullet.scd.yahoo.com with NNFMP; 10 Nov 2006 09:25:27 -0000\r\nDate: Fri, 10 Nov 2006 09:25:26 -0000\r\nTo: neat@yahoogroups.com\r\nMessage-ID: &lt;ej1gi6+tq72@...&gt;\r\nIn-Reply-To: &lt;ej1e81+70up@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=&quot;ISO-8859-1&quot;\r\nContent-Transfer-Encoding: quoted-printable\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-compose\r\nFrom: &quot;iwaneicher&quot; &lt;reicher@...&gt;\r\nSubject: Re: Null Pointer Exception within Class NEATSpecieManager.java\r\nX-Yahoo-Group-Post: member; u=288041957; y=F5XFyT--6dzpvMT1ZLU2NNNt55eqmLSXVD4jG1zoGAudrSLIYg\r\nX-Yahoo-Profile: iwaneicher\r\n\r\nHi again,\nWe just looked through the relevant code and most probably found =\r\na bug\nwithin the class InnovationDatabase.java. Here the code from line 90\n=\r\nto 116\n\nfor (popIdx =3D 0; popIdx &lt; templates.length; popIdx++) {\n\t// outpu=\r\nts are last nodes.\n\tif (featureSelection) {\n\t\t// start with one link to eac=\r\nh output, allows feature selection\n\t\tlinks =3D new NEATLinkGene[outputs] ;\n=\r\n\t\tfor (i =3D 0; i &lt; outputs; i++) {\n\t\t\tlinks[i] =3D\nthis.submitLinkInnovati=\r\non(nodes[this.ran.nextInt(inputs)].id(),\nnodes[inputs + i].id());\n\t\t\tlinks[=\r\ni].setWeight(MathUtils.nextPlusMinusOne());\n\t\t}\n\t} else {\n\t\t// start with e=\r\nach input to each output, doesn&#39;t allow feature selection\n\t\tlinks =3D new N=\r\nEATLinkGene[inputs * outputs] ;\n\t\tfor (i =3D 0; i &lt; outputs; i++) {\n\t\t\tfor =\r\n(j =3D 0; j &lt; inputs; j++) {\n\t\t\t\tlinks[(i * outputs) + j] =3D\nthis.submitLi=\r\nnkInnovation(nodes[j].id(), nodes[inputs + i].id());\n\t\t\t\tlinks[(i * outputs=\r\n) + j].setWeight(MathUtils.nextPlusMinusOne());\n\t\t\t}\n\t\t}\n\t}\n\t//links[2] =3D=\r\n this.submitLinkInnovation(nodes[0].id(), nodes[3].id());\n\t//links[2].setWe=\r\night(MathUtils.nextPlusMinusOne());\n\t//links[3] =3D this.submitLinkInnovati=\r\non(nodes[1].id(), nodes[3].id());\n\t//links[3].setWeight(MathUtils.nextPlusM=\r\ninusOne());\n\t//links[3] =3D this.submitLinkInnovation(nodes[3].id(), nodes[=\r\n2].id());\n\t//links[3].setWeight(MathUtils.nextPlusMinusOne());\n\ttemplates[p=\r\nopIdx] =3D this.createNEATChromosome(nodes, links, features);\n}\n\n\nAt lines =\r\n104 and 105 it should be &quot;links[(i * inputs) + j] =3D &quot; instead\nof &quot;links[(=\r\ni * outputs) + j] =3D &quot;. Otherwise the array will not be\ninitialized proper=\r\nly.\n\nCan you please check if that is really a bug?\n\n\nThanks\n\nIwan\n\n\n\n\n--- I=\r\nn neat@yahoogroups.com, &quot;iwaneicher&quot; &lt;reicher@...&gt; wrote:\n&gt;\n&gt; Hi,\n&gt; If we i=\r\nnitialize NEAT with any population size, 28 input neurons, 18\n&gt; output neur=\r\nons and config parameter FEATURE.SELECTION=3Dfalse, we get a\n&gt; null pointer=\r\n exception within the the method &quot;compatibilityScore&quot; of\n&gt; the class &quot;NEATS=\r\npecieManager&quot;. The Exception looks as follows:\n&gt; \n&gt; Exception in thread &quot;ma=\r\nin&quot; java.lang.NullPointerException\n&gt; \tat\n&gt;\norg.neat4j.neat.core.NEATSpecieM=\r\nanager.compatibilityScore(NEATSpecieManager.java:47)\n&gt; \tat org.neat4j.neat.=\r\ncore.NEATSpecie.isCompatable(NEATSpecie.java:107)\n&gt; \tat org.neat4j.neat.ga.=\r\ncore.Specie.addSpecieMember(Specie.java:110)\n&gt; \tat org.neat4j.neat.core.NEA=\r\nTSpecie.addSpecieMember(NEATSpecie.java:46)\n&gt; \tat\n&gt;\nneat4j.ga.RMINEATGeneti=\r\ncAlgorithm.speciatePopulation(RMINEATGeneticAlgorithm.java:138)\n&gt; \tat\n&gt;\nnea=\r\nt4j.ga.RMINEATGeneticAlgorithm.runEvolutionCycle(RMINEATGeneticAlgorithm.ja=\r\nva:189)\n&gt; \tat\n&gt;\nneat4j.ga.RMINEATGeneticAlgorithm.runEpoch(RMINEATGeneticAl=\r\ngorithm.java:175)\n&gt; \tat neat4j.RobeeEvolution.evolve(RobeeEvolution.java:33=\r\n7)\n&gt; \tat neat4j.RobeeEvolution.main(RobeeEvolution.java:356)\n&gt; \n&gt; We set a =\r\nbreak point at line 47 before the the following if-clause is\n&gt; executed: \n&gt;=\r\n \n&gt; if (((NEATGene)applicantGenes[applicantIdx]).getInnovationNumber() =3D=\r\n=3D\n&gt; ((NEATGene)repGenes[repIdx]).getInnovationNumber())\n&gt; \n&gt; We realized,=\r\n that the applicantGenes array has a size of 550 but from\n&gt; id 380 there ar=\r\ne no NEATLinkGENE instances but only null pointers. The\n&gt; same is with repG=\r\nenes array.\n&gt; \n&gt; We guess, that there&#39;s no full mesh initialized, so thats =\r\nwhy some of\n&gt; the links are initialized with null. 28 times 18 is 504, so t=\r\nhere must\n&gt; be at least 504 NEATLinkGENES. Maybe there&#39;s a bug, maybe we\n&gt; =\r\nunderstood something wrongly and have to adjust a config parameter.\n&gt; \n&gt; An=\r\nybody experienced the same problem? Is that a bug?\n&gt; \n&gt; Thanks\n&gt; \n&gt; Iwan\n&gt;\n=\r\n\n\n\n"}}